# Generated by Django 5.1.4 on 2024-12-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="observations",
            field=models.TextField(default="", max_length=2048),
        ),
    ]
