# Generated by Django 5.1.4 on 2024-12-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_car_observations"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="description",
            field=models.TextField(default="", max_length=4096),
        ),
    ]
