# Generated by Django 5.1.4 on 2024-12-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_carmodel_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="fuel_type",
            field=models.CharField(default="Benzinas", max_length=64),
            preserve_default=False,
        ),
    ]
