# Generated by Django 5.1.4 on 2024-12-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_carmodel_fuel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(default="", max_length=4096),
        ),
    ]
