# Generated by Django 5.1.4 on 2025-01-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
