# Generated by Django 5.1.4 on 2025-01-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0009_remove_order_total_price_alter_orderline_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderline",
            name="price",
        ),
    ]
